// AUTO-GENERATED by scripts/generate.ts. Do not edit.
import type { BindOperation } from "./client.ts";
import * as accountActivity from "./services/account-activity.ts";
import * as activity from "./services/activity.ts";
import * as articles from "./services/articles.ts";
import * as bookmarks from "./services/bookmarks.ts";
import * as broadcasts from "./services/broadcasts.ts";
import * as chats from "./services/chats.ts";
import * as communities from "./services/communities.ts";
import * as communityNotes from "./services/community-notes.ts";
import * as compliance from "./services/compliance.ts";
import * as connections from "./services/connections.ts";
import * as counts from "./services/counts.ts";
import * as directMessages from "./services/direct-messages.ts";
import * as general from "./services/general.ts";
import * as likes from "./services/likes.ts";
import * as lists from "./services/lists.ts";
import * as media from "./services/media.ts";
import * as mutes from "./services/mutes.ts";
import * as news from "./services/news.ts";
import * as posts from "./services/posts.ts";
import * as search from "./services/search.ts";
import * as spaces from "./services/spaces.ts";
import * as stream from "./services/stream.ts";
import * as trends from "./services/trends.ts";
import * as tweets from "./services/tweets.ts";
import * as usage from "./services/usage.ts";
import * as users from "./services/users.ts";
import * as webhooks from "./services/webhooks.ts";
export const makeApi = (bind: BindOperation) => ({
  accountActivity: {
    createAccountActivitySubscription: bind(
      accountActivity.createAccountActivitySubscription,
    ),
    deleteAccountActivitySubscription: bind(
      accountActivity.deleteAccountActivitySubscription,
    ),
    getAccountActivitySubscriptionCount: bind(
      accountActivity.getAccountActivitySubscriptionCount,
    ),
    getAccountActivitySubscriptions: bind(
      accountActivity.getAccountActivitySubscriptions,
    ),
    validateAccountActivitySubscription: bind(
      accountActivity.validateAccountActivitySubscription,
    ),
  },
  activity: {
    createActivitySubscription: bind(activity.createActivitySubscription),
    deleteActivitySubscription: bind(activity.deleteActivitySubscription),
    deleteActivitySubscriptionsByIds: bind(
      activity.deleteActivitySubscriptionsByIds,
    ),
    getActivitySubscriptions: bind(activity.getActivitySubscriptions),
    updateActivitySubscription: bind(activity.updateActivitySubscription),
  },
  articles: {
    articleCreateDraft: bind(articles.articleCreateDraft),
    articlePublish: bind(articles.articlePublish),
  },
  bookmarks: {
    createUsersBookmarkFolder: bind(bookmarks.createUsersBookmarkFolder),
    deleteUsersBookmark: bind(bookmarks.deleteUsersBookmark),
  },
  broadcasts: {
    createScheduledBroadcast: bind(broadcasts.createScheduledBroadcast),
    deleteScheduledBroadcast: bind(broadcasts.deleteScheduledBroadcast),
    getScheduledBroadcast: bind(broadcasts.getScheduledBroadcast),
    goLiveScheduledBroadcast: bind(broadcasts.goLiveScheduledBroadcast),
    listScheduledBroadcasts: bind(broadcasts.listScheduledBroadcasts),
    sendBroadcastChat: bind(broadcasts.sendBroadcastChat),
    updateScheduledBroadcast: bind(broadcasts.updateScheduledBroadcast),
  },
  chats: {
    addChatGroupMembers: bind(chats.addChatGroupMembers),
    addConversationKeys: bind(chats.addConversationKeys),
    addUserPublicKey: bind(chats.addUserPublicKey),
    chatMediaDownload: bind(chats.chatMediaDownload),
    chatMediaUploadAppend: bind(chats.chatMediaUploadAppend),
    chatMediaUploadFinalize: bind(chats.chatMediaUploadFinalize),
    chatMediaUploadInitialize: bind(chats.chatMediaUploadInitialize),
    createChatConversation: bind(chats.createChatConversation),
    getChatConversation: bind(chats.getChatConversation),
    getChatConversationEvents: bind(chats.getChatConversationEvents),
    getChatConversations: bind(chats.getChatConversations),
    getUsersPublicKey: bind(chats.getUsersPublicKey),
    getUsersPublicKeys: bind(chats.getUsersPublicKeys),
    initializeChatGroup: bind(chats.initializeChatGroup),
    markChatConversationRead: bind(chats.markChatConversationRead),
    sendChatMessage: bind(chats.sendChatMessage),
    sendChatTypingIndicator: bind(chats.sendChatTypingIndicator),
  },
  communities: {
    getCommunitiesById: bind(communities.getCommunitiesById),
    searchCommunities: bind(communities.searchCommunities),
  },
  communityNotes: {
    createCommunityNotes: bind(communityNotes.createCommunityNotes),
    deleteCommunityNotes: bind(communityNotes.deleteCommunityNotes),
    evaluateCommunityNotes: bind(communityNotes.evaluateCommunityNotes),
    searchCommunityNotesWritten: bind(
      communityNotes.searchCommunityNotesWritten,
    ),
    searchEligiblePosts: bind(communityNotes.searchEligiblePosts),
  },
  compliance: {
    createComplianceJobs: bind(compliance.createComplianceJobs),
    getComplianceJobs: bind(compliance.getComplianceJobs),
    getComplianceJobsById: bind(compliance.getComplianceJobsById),
  },
  connections: {
    deleteAllConnections: bind(connections.deleteAllConnections),
    deleteConnectionsByEndpoint: bind(connections.deleteConnectionsByEndpoint),
    deleteConnectionsByUuids: bind(connections.deleteConnectionsByUuids),
    getConnectionHistory: bind(connections.getConnectionHistory),
  },
  counts: {
    getPostsCountsAll: bind(counts.getPostsCountsAll),
    getPostsCountsRecent: bind(counts.getPostsCountsRecent),
  },
  directMessages: {
    blockUsersDms: bind(directMessages.blockUsersDms),
    createDirectMessagesByConversationId: bind(
      directMessages.createDirectMessagesByConversationId,
    ),
    createDirectMessagesByParticipantId: bind(
      directMessages.createDirectMessagesByParticipantId,
    ),
    createDirectMessagesConversation: bind(
      directMessages.createDirectMessagesConversation,
    ),
    deleteDirectMessagesEvents: bind(directMessages.deleteDirectMessagesEvents),
    dmConversationsMediaDownload: bind(
      directMessages.dmConversationsMediaDownload,
    ),
    getDirectMessagesEvents: bind(directMessages.getDirectMessagesEvents),
    getDirectMessagesEventsByConversationId: bind(
      directMessages.getDirectMessagesEventsByConversationId,
    ),
    getDirectMessagesEventsById: bind(
      directMessages.getDirectMessagesEventsById,
    ),
    getDirectMessagesEventsByParticipantId: bind(
      directMessages.getDirectMessagesEventsByParticipantId,
    ),
    unblockUsersDms: bind(directMessages.unblockUsersDms),
  },
  general: { getOpenApiSpec: bind(general.getOpenApiSpec) },
  likes: {
    getPostsLikingUsers: bind(likes.getPostsLikingUsers),
    likePost: bind(likes.likePost),
    unlikePost: bind(likes.unlikePost),
  },
  lists: {
    addListsMember: bind(lists.addListsMember),
    createLists: bind(lists.createLists),
    deleteLists: bind(lists.deleteLists),
    getListsById: bind(lists.getListsById),
    getListsFollowers: bind(lists.getListsFollowers),
    getListsMembers: bind(lists.getListsMembers),
    getListsPosts: bind(lists.getListsPosts),
    pinList: bind(lists.pinList),
    removeListsMemberByUserId: bind(lists.removeListsMemberByUserId),
    unfollowList: bind(lists.unfollowList),
    unpinList: bind(lists.unpinList),
    updateLists: bind(lists.updateLists),
  },
  media: {
    appendMediaUpload: bind(media.appendMediaUpload),
    createMediaMetadata: bind(media.createMediaMetadata),
    createMediaSubtitles: bind(media.createMediaSubtitles),
    deleteMediaSubtitles: bind(media.deleteMediaSubtitles),
    finalizeMediaUpload: bind(media.finalizeMediaUpload),
    getMediaAnalytics: bind(media.getMediaAnalytics),
    getMediaByMediaKey: bind(media.getMediaByMediaKey),
    getMediaByMediaKeys: bind(media.getMediaByMediaKeys),
    getMediaUploadStatus: bind(media.getMediaUploadStatus),
    initializeMediaUpload: bind(media.initializeMediaUpload),
    mediaUpload: bind(media.mediaUpload),
  },
  mutes: { unmuteUser: bind(mutes.unmuteUser) },
  news: { getNews: bind(news.getNews) },
  posts: {
    createPosts: bind(posts.createPosts),
    createUsersBookmark: bind(posts.createUsersBookmark),
    deletePosts: bind(posts.deletePosts),
    getPostsAnalytics: bind(posts.getPostsAnalytics),
    getPostsById: bind(posts.getPostsById),
    getPostsByIds: bind(posts.getPostsByIds),
    getPostsQuotedPosts: bind(posts.getPostsQuotedPosts),
    getPostsRepostedBy: bind(posts.getPostsRepostedBy),
    getPostsReposts: bind(posts.getPostsReposts),
    getTrendsByWoeid: bind(posts.getTrendsByWoeid),
    getUsersBookmarkFolders: bind(posts.getUsersBookmarkFolders),
    getUsersBookmarks: bind(posts.getUsersBookmarks),
    getUsersBookmarksByFolderId: bind(posts.getUsersBookmarksByFolderId),
    getUsersLikedPosts: bind(posts.getUsersLikedPosts),
    getUsersMentions: bind(posts.getUsersMentions),
    getUsersPosts: bind(posts.getUsersPosts),
    getUsersTimeline: bind(posts.getUsersTimeline),
    hidePostsReply: bind(posts.hidePostsReply),
    repostPost: bind(posts.repostPost),
    unrepostPost: bind(posts.unrepostPost),
  },
  search: {
    searchNews: bind(search.searchNews),
    searchPostsAll: bind(search.searchPostsAll),
    searchPostsRecent: bind(search.searchPostsRecent),
  },
  spaces: {
    getSpacesBuyers: bind(spaces.getSpacesBuyers),
    getSpacesByCreatorIds: bind(spaces.getSpacesByCreatorIds),
    getSpacesById: bind(spaces.getSpacesById),
    getSpacesByIds: bind(spaces.getSpacesByIds),
    getSpacesPosts: bind(spaces.getSpacesPosts),
    searchSpaces: bind(spaces.searchSpaces),
  },
  stream: {
    activityStream: bind(stream.activityStream),
    getRuleCounts: bind(stream.getRuleCounts),
    streamLabelsCompliance: bind(stream.streamLabelsCompliance),
    streamLikesCompliance: bind(stream.streamLikesCompliance),
    streamLikesFirehose: bind(stream.streamLikesFirehose),
    streamLikesSample10: bind(stream.streamLikesSample10),
    streamPosts: bind(stream.streamPosts),
    streamPostsCompliance: bind(stream.streamPostsCompliance),
    streamPostsFirehose: bind(stream.streamPostsFirehose),
    streamPostsFirehoseEn: bind(stream.streamPostsFirehoseEn),
    streamPostsFirehoseJa: bind(stream.streamPostsFirehoseJa),
    streamPostsFirehoseKo: bind(stream.streamPostsFirehoseKo),
    streamPostsFirehosePt: bind(stream.streamPostsFirehosePt),
    streamPostsSample: bind(stream.streamPostsSample),
    streamPostsSample10: bind(stream.streamPostsSample10),
    streamUsersCompliance: bind(stream.streamUsersCompliance),
  },
  trends: {
    getTrendsPersonalizedTrends: bind(trends.getTrendsPersonalizedTrends),
  },
  tweets: {
    getRules: bind(tweets.getRules),
    updateRules: bind(tweets.updateRules),
  },
  usage: { getUsage: bind(usage.getUsage) },
  users: {
    followList: bind(users.followList),
    followUser: bind(users.followUser),
    getUsersAffiliates: bind(users.getUsersAffiliates),
    getUsersBlocking: bind(users.getUsersBlocking),
    getUsersById: bind(users.getUsersById),
    getUsersByIds: bind(users.getUsersByIds),
    getUsersByUsername: bind(users.getUsersByUsername),
    getUsersByUsernames: bind(users.getUsersByUsernames),
    getUsersFollowedLists: bind(users.getUsersFollowedLists),
    getUsersFollowers: bind(users.getUsersFollowers),
    getUsersFollowing: bind(users.getUsersFollowing),
    getUsersListMemberships: bind(users.getUsersListMemberships),
    getUsersMe: bind(users.getUsersMe),
    getUsersMuting: bind(users.getUsersMuting),
    getUsersOwnedLists: bind(users.getUsersOwnedLists),
    getUsersPinnedLists: bind(users.getUsersPinnedLists),
    getUsersRepostsOfMe: bind(users.getUsersRepostsOfMe),
    muteUser: bind(users.muteUser),
    searchUsers: bind(users.searchUsers),
    unfollowUser: bind(users.unfollowUser),
  },
  webhooks: {
    createWebhookReplayJob: bind(webhooks.createWebhookReplayJob),
    createWebhooks: bind(webhooks.createWebhooks),
    createWebhooksStreamLink: bind(webhooks.createWebhooksStreamLink),
    deleteWebhooks: bind(webhooks.deleteWebhooks),
    deleteWebhooksStreamLink: bind(webhooks.deleteWebhooksStreamLink),
    getWebhooks: bind(webhooks.getWebhooks),
    getWebhooksStreamLinks: bind(webhooks.getWebhooksStreamLinks),
    validateWebhooks: bind(webhooks.validateWebhooks),
  },
});
export type Api = ReturnType<typeof makeApi>;
