// AUTO-GENERATED by scripts/generate.ts from xdevplatform/xdk@84c26540df30c0b798e50e34151c56d5d262ba1c (specs/openapi.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import { XProtocol, type XOpError, type XOpContext } from "../protocol.ts";
import { XParseError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { XOpError, XOpContext };

export interface GetOpenApiSpecRequest {}
export const GetOpenApiSpecRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({ method: "GET", uri: "/2/openapi.json", code: 200 }),
  ),
).annotate({
  identifier: "GetOpenApiSpecRequest",
}) as any as S.Schema<GetOpenApiSpecRequest>;

export type GetOpenApiSpecResponse = unknown;
export const GetOpenApiSpecResponse = /*@__PURE__*/ S.suspend(() =>
  S.Unknown.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "GetOpenApiSpecResponse",
}) as any as S.Schema<GetOpenApiSpecResponse>;

export type GetOpenApiSpecError = XOpError;
/** Get OpenAPI Spec. Retrieves the full OpenAPI Specification in JSON format. (See https://github.com/OAI/OpenAPI-Specification/blob/master/README.md) */
export const getOpenApiSpec: API.OperationMethod<
  GetOpenApiSpecRequest,
  GetOpenApiSpecResponse,
  GetOpenApiSpecError,
  XOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetOpenApiSpecRequest,
  output: GetOpenApiSpecResponse,
  errors: [XParseError],
  protocol: XProtocol,
  retry: Retry.Retry,
  operationName: "getOpenApiSpec",
}));
